import assert from 'node:assert/strict';
import { INITIAL_BOOKS } from './fixtures/libraryFixtures';
import { ConflictError, NotFoundError, ValidationError } from '../server/errors/ApplicationErrors';
import { InMemoryBookRepository } from '../server/repositories/BookRepository';
import { InMemoryAuditLogRepository, InMemoryBookmarkRepository, InMemoryCollectionRepository, InMemoryHighlightRepository, InMemoryReadingProgressRepository, InMemoryReviewRepository, InMemoryRightsRepository } from '../server/repositories/LibraryRepositories';
import { AuditService, BookmarkService, CollectionService, HighlightService, ReadingService, ReviewService, RightsService } from '../server/services/LibraryServices';
import { validateCollection, validateProgress, validateReview } from '../server/validators/libraryValidators';

const book = structuredClone(INITIAL_BOOKS[0]);
const books = new InMemoryBookRepository([book]);
const audit = new AuditService(new InMemoryAuditLogRepository());
const reading = new ReadingService(books, new InMemoryReadingProgressRepository(), audit);
const bookmarks = new BookmarkService(books, new InMemoryBookmarkRepository(), audit);
const highlights = new HighlightService(books, new InMemoryHighlightRepository(), audit);
const collections = new CollectionService(books, new InMemoryCollectionRepository(), audit);
const reviews = new ReviewService(books, new InMemoryReviewRepository(), audit);
const rights = new RightsService(books, new InMemoryRightsRepository(), audit);
const input = { userId: 'strict-demo-user', editionId: book.editions[0].id, currentChapterIndex: 0, currentScrollPercent: 10, completedPercent: 20, totalSecondsSpent: 60, clientSequence: 1, clientUpdatedAt: '2026-08-16T00:00:00.000Z' };

const progress = await reading.upsert(book.id, input);
assert.equal(progress.completed, false);
await assert.rejects(() => reading.upsert(book.id, { ...input, currentChapterIndex: 999 }), (error: unknown) => error instanceof ValidationError);
const bookmark = await bookmarks.create({ userId: input.userId, bookId: book.id, editionId: input.editionId, chapterIndex: 0, progressPercent: 20, title: 'Start' });
await assert.rejects(() => bookmarks.create({ userId: input.userId, bookId: book.id, editionId: input.editionId, chapterIndex: 0, progressPercent: 20, title: 'Duplicate' }), (error: unknown) => error instanceof ConflictError);
await bookmarks.delete(bookmark.id, input.userId);
await assert.rejects(() => bookmarks.delete(bookmark.id, input.userId), (error: unknown) => error instanceof NotFoundError);
const highlight = await highlights.create({ userId: input.userId, bookId: book.id, chapterIndex: 0, selectedText: 'Service-level note', color: 'moss', note: 'first' });
assert.equal((await highlights.updateNote(highlight.id, input.userId, 'second')).note, 'second');
await assert.rejects(() => collections.create({ userId: input.userId, title: 'Missing ref', isPublic: false, colorTheme: '#000000', bookIds: ['missing-book'] }), (error: unknown) => error instanceof NotFoundError);
const collection = await collections.create(validateCollection({ userId: input.userId, title: 'Service Shelf', isPublic: false, colorTheme: '#000000', bookIds: [book.id] }));
assert.equal(collection.bookIds[0], book.id);
const review = await reviews.create(validateReview({ userId: input.userId, userName: 'Strict User', userAvatar: 'https://example.test/avatar', bookId: book.id, rating: 5, title: 'Service review', content: 'Business logic is exercised directly.' }));
assert.equal(review.isVerifiedReader, false);
await assert.rejects(() => reviews.create(validateReview({ userId: input.userId, userName: 'Strict User', userAvatar: 'https://example.test/avatar', bookId: book.id, rating: 4, title: 'Duplicate', content: 'Duplicate.' })), (error: unknown) => error instanceof ConflictError);
const rightsRecord = await rights.create({ bookId: book.id, editionId: input.editionId, status: 'PUBLIC_DOMAIN', licenseType: 'Test', source: 'Test', evidence: 'Test evidence', verificationMethod: 'MANUAL_REVIEW', territory: 'WORLDWIDE', attribution: 'Test', verifiedAt: '2026-08-15T00:00:00.000Z' }, input.userId);
assert.equal(rightsRecord.bookId, book.id);
assert.ok((await audit.list()).length >= 6);
assert.throws(() => validateProgress({ ...input, completedPercent: 10, currentScrollPercent: 20 }), (error: unknown) => error instanceof ValidationError);
console.log('P1 library service checks passed.');
