import { ForestRegionId } from '../types';

export const BRAND_CONFIG = {
  name: 'NEXARA',
  nameAr: 'نكسارا',
  tagline: 'A Living Forest of Literature',
  taglineAr: 'غابة حية من عوالم الأدب والفكر',
  heroTitle: 'Enter the Forest of Stories',
  heroTitleAr: 'ادخل غابة الحكايات',
  heroSubtitle: 'A living library of stories, ideas, poetry and worlds waiting to be discovered.',
  heroSubtitleAr: 'مكتبة حية من الحكايات، الأفكار، الشعر والعوالم التي تنتظر من يكتشفها.',
  
  colors: {
    forestDeep: '#07110D',
    forestDark: '#0B1712',
    forestCard: '#10231A',
    forestHover: '#173125',
    ink: '#11100E',
    paper: '#E8E0CF',
    paperMuted: '#BDB5A5',
    moss: '#687B61',
    mossLight: '#89977C',
    gold: '#B89A5A',
    goldLight: '#D2BB82',
    burgundy: '#4A2528',
  },

  recommendationWeights: {
    genreSimilarity: 0.25,
    authorSimilarity: 0.20,
    readingHistory: 0.15,
    themeSimilarity: 0.15,
    coReadBehavior: 0.10,
    editorialCuration: 0.10,
    popularity: 0.05,
  },

  forestRegions: [
    {
      id: 'philosophy' as ForestRegionId,
      name: 'The Valley of Philosophy',
      nameAr: 'وادي الفلسفة',
      description: 'Where deep thought and timeless inquiries echo through ancient pines.',
      descriptionAr: 'حيث ترتد أصداء الفكر العميق والأسئلة الخالدة بين أشجار الصنوبر العتيقة.',
      color: '#B89A5A',
      icon: 'Compass',
      ambientSound: 'wind',
      bounds: { xMin: 5, xMax: 35, yMin: 10, yMax: 40 },
    },
    {
      id: 'ancient-grove' as ForestRegionId,
      name: 'The Ancient Grove',
      nameAr: 'الدوحة القديمة',
      description: 'Foundations of human wisdom, epics, and classical heritage.',
      descriptionAr: 'أصول الحكمة الإنسانية والملاحم الخالدة والتراث الكلاسيكي العريق.',
      color: '#687B61',
      icon: 'TreePine',
      ambientSound: 'fireplace',
      bounds: { xMin: 40, xMax: 70, yMin: 10, yMax: 40 },
    },
    {
      id: 'poetry' as ForestRegionId,
      name: 'The Garden of Poetry',
      nameAr: 'روضة الشعر',
      description: 'Stanzas drifting like fallen leaves, lyrical rhythms, and mystical verse.',
      descriptionAr: 'أبيات تتهادى كأوراق الخريف، وأوزان موسيقية وقصائد صوفية بديعة.',
      color: '#89977C',
      icon: 'Feather',
      ambientSound: 'rain',
      bounds: { xMin: 70, xMax: 95, yMin: 15, yMax: 45 },
    },
    {
      id: 'river-of-stories' as ForestRegionId,
      name: 'The River of Stories',
      nameAr: 'نهر الروايات والحكايات',
      description: 'Flowing narratives, enduring novels, and characters living across time.',
      descriptionAr: 'سرديات متدفقة، وروايات خالدة وشخصيات تنبض بالحياة عبر الأزمان.',
      color: '#D2BB82',
      icon: 'Waves',
      ambientSound: 'rain',
      bounds: { xMin: 15, xMax: 50, yMin: 45, yMax: 75 },
    },
    {
      id: 'midnight-library' as ForestRegionId,
      name: 'The Midnight Library',
      nameAr: 'مكتبة منتصف الليل',
      description: 'Existential solitude, dark themes, psychological depths, and nocturnal reflections.',
      descriptionAr: 'عزلة وجودية، وظلال نفسية عميقة وتأملات ليلية هادئة.',
      color: '#4A2528',
      icon: 'Moon',
      ambientSound: 'night-forest',
      bounds: { xMin: 55, xMax: 90, yMin: 45, yMax: 75 },
    },
    {
      id: 'archive-woods' as ForestRegionId,
      name: 'The Archive Woods',
      nameAr: 'أحراش الأرشيف والتاريخ',
      description: 'Historiography, chronicles, civilizational manuscripts, and scientific treatises.',
      descriptionAr: 'دراسات تاريخية ومخطوطات حضارية وأبحاث علمية موثقة.',
      color: '#BDB5A5',
      icon: 'Archive',
      ambientSound: 'library',
      bounds: { xMin: 10, xMax: 45, yMin: 75, yMax: 95 },
    },
    {
      id: 'open-fields' as ForestRegionId,
      name: 'The Open Fields',
      nameAr: 'الحقول المفتوحة',
      description: 'Fresh literary horizons, emerging voices, open essays, and untamed discoveries.',
      descriptionAr: 'آفاق أدبية متجددة، مقالات منوعة واكتشافات بكر تنتظر القارئ.',
      color: '#89977C',
      icon: 'Sun',
      ambientSound: 'wind',
      bounds: { xMin: 50, xMax: 90, yMin: 75, yMax: 95 },
    },
  ],

  moods: [
    { id: 'Calm', name: 'Calm', nameAr: 'سكينة وهدوء', description: 'Serene, meditative prose and gentle verse', icon: 'Wind', color: '#89977C' },
    { id: 'Melancholic', name: 'Melancholic', nameAr: 'شجن وتأمل', description: 'Nostalgic, elegiac depths and longing', icon: 'CloudRain', color: '#687B61' },
    { id: 'Hopeful', name: 'Hopeful', nameAr: 'أمل وتفاؤل', description: 'Uplifting human resilience and renewal', icon: 'Sun', color: '#D2BB82' },
    { id: 'Dark', name: 'Dark', nameAr: 'غموض وظلال', description: 'Psychological tension and existential gravity', icon: 'Moon', color: '#4A2528' },
    { id: 'Curious', name: 'Curious', nameAr: 'شغف وفضول', description: 'Intellectual wonders and uncharted vistas', icon: 'Sparkles', color: '#B89A5A' },
    { id: 'Romantic', name: 'Romantic', nameAr: 'وجد وعاطفة', description: 'Passionate devotion and poetic beauty', icon: 'Heart', color: '#4A2528' },
    { id: 'Intellectual', name: 'Intellectual', nameAr: 'عمق فكري', description: 'Rigorous philosophy, sociology, and ethics', icon: 'BookOpen', color: '#B89A5A' },
    { id: 'Adventurous', name: 'Adventurous', nameAr: 'رحلات ومغامرة', description: 'Epic travels, wanderers, and discoveries', icon: 'Compass', color: '#D2BB82' },
    { id: 'Reflective', name: 'Reflective', nameAr: 'محاسبة وبصيرة', description: 'Introspective memoirs and philosophical solitudes', icon: 'Eye', color: '#89977C' },
  ],
};
